#!/bin/bash

node test/tput.js "$@" | tee out
out=$(git diff --color=always --no-index test/terminfo out)
rm out

if test -n "$out"; then
  echo "$out" | less -c -R
else
  echo 'Files are identical.'
fi
